# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1, verbose_name='State')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
            ],
        ),
    ]
