version: '2'
services:
  data:
    image: alpine:latest
    volumes:
      - /var/lib/postgresql/data
    command: 'true'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=gamehub
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes_from:
      - data
    ports:
      - '5432'

  memcached:
    image: memcached:latest
    ports:
      - '11211'

  gamehub:
    build: .
    volumes:
      - .:/home/admin/gamehub
    ports:
      - "8000:8000"
    links:
      - db
      - memcached
